In [ ]:
import numpy as np

arr = np.array([1 , 2, 3])

print(arr)

print(type(arr))

[1 2 3]
<class 'numpy.ndarray'>


In [ ]:

print(len(arr))
print(arr.shape)

3
(3,)


In [ ]:
#append
x = np.array([1, 2, 3, 4, 5])
y = np.append(x, [50, 70])
print(y)


[ 1  2  3  4  5 50 70]


In [ ]:
#delete
x = np.array([1, 2, 3, 4, 5])
y = np.delete(x, 2)
print(x)
print(y)


[1 2 3 4 5]
[1 2 4 5]


In [ ]:
#sorting
x = np.array([7, 8, 3, 10, 5])
sorted_x = np.sort(x)
print(sorted_x)
print(sorted_x[::-1]) # sort ascending # decending sort slicing

[ 3  5  7  8 10]
[10  8  7  5  3]


In [ ]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(arr_2d)

print(len(arr_2d))
print(arr_2d.shape)
print(arr_2d.ndim)  #ndim for dimension checking , checking the funtionality of numpy

[[1 2 3]
 [4 5 6]]
2
(2, 3)
2


In [ ]:

#indexing

arr = np.array([1, 2, 3, 4])
print(arr[0])
print(arr[-1])

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('4th element on 2nd dim: ', arr[0, 3])
print('5th element on 2nd dim: ', arr[1, 4])

1
4
4th element on 2nd dim:  4
5th element on 2nd dim:  10


In [ ]:
#Slicing -> [start:end:step]
#The result includes the start index, but excludes the end index.

In [ ]:

arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[4:])
print(arr[:4])
print(arr[-3:-1])
print(arr[1:5:2])

[5 6 7]
[1 2 3 4]
[5 6]
[2 4]


In [ ]:
#Slicing 2-D Arrays

#From the second element, slice elements from index 1 to index 4 (not included):

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[1, 1:4])

#from both elements, slice index 1 to index 4 (not included)
print(arr[0:2, 1:4]) # first part for row select(eikhane 2) , 2nd part for element select


[7 8 9]
[[2 3 4]
 [7 8 9]]


In [ ]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print (arr)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [ ]:
print(arr[0:2],) # getting the full row
print(arr[:, 0]) # column
print(arr[0, :]) # row

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[1 6]
[1 2 3 4 5]


In [ ]:
#special numpy functions

In [ ]:
#zero matrix
x=np.zeros(2) #one d array in numpy
print(x)

[0. 0.]


In [ ]:
y=np.zeros((4,2)) #2d array
print(y)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [ ]:
a = np.array([3, 4, 5])
b = np.array([[1,2,3],[4,5,6]])

print(np.sum(a))
print(np.sum(b))

print(np.prod(a))
print(np.prod(b))

12
21
60
720


In [ ]:
print(np.sum(b, axis=0)) # column wise addition when axis =0
print(np.sum(b, axis=1)) # row  wise addition when axis = 1

[5 7 9]
[ 6 15]


In [ ]:

#logical indexing

print(b > 2)
print(b[b>2])

[[False False  True]
 [ True  True  True]]
[3 4 5 6]


In [ ]:

print(b[ b > 2 ])
b[ b > 2 ] = 100 # replacing with 100
print(b)

[3 4 5 6]
[[  1   2 100]
 [100 100 100]]


In [ ]:
#iterating numpy array

arr = np.array([1, 2, 3])
for x in arr:
  print(x)

arr = np.array([[1, 2, 3], [4, 5, 6]])
for x in arr:
  print(x)

1
2
3
[1 2 3]
[4 5 6]


In [ ]:
#nested loop
arr = np.array([[1, 2, 3], [4, 5, 6]])
for i in arr:
  for j in i:
    print(j)

1
2
3
4
5
6


In [ ]:
#linspace
x = np.linspace(0, 100, 51) #even number #diff always same
print(x)

y = np.linspace(0,12,8) # start,end,numbers
print(y)


[  0.   2.   4.   6.   8.  10.  12.  14.  16.  18.  20.  22.  24.  26.
  28.  30.  32.  34.  36.  38.  40.  42.  44.  46.  48.  50.  52.  54.
  56.  58.  60.  62.  64.  66.  68.  70.  72.  74.  76.  78.  80.  82.
  84.  86.  88.  90.  92.  94.  96.  98. 100.]
[ 0.          1.71428571  3.42857143  5.14285714  6.85714286  8.57142857
 10.28571429 12.        ]


In [ ]:

#Numpy array element wise operation
print(x + 10)

[ 10.  12.  14.  16.  18.  20.  22.  24.  26.  28.  30.  32.  34.  36.
  38.  40.  42.  44.  46.  48.  50.  52.  54.  56.  58.  60.  62.  64.
  66.  68.  70.  72.  74.  76.  78.  80.  82.  84.  86.  88.  90.  92.
  94.  96.  98. 100. 102. 104. 106. 108. 110.]


In [ ]:
#using customized arithmetic operations
y = np.array([1, 2, 3, 4])
z = np.array([10, 10, 20, 30])
print(y ** 2)
print(2*y + z)

[ 1  4  9 16]
[12 14 26 38]


# Pandas

In [ ]:
import pandas as pd

In [ ]:

#dataframes-> 2 dimensional data structure

import pandas as pd

data = {
  "name": ['Arif', 'Nafis', 'Hasan'],
  "age": [35, 30, 40]
}

#load data into a DataFrame object:
df = pd.DataFrame(data)

print(df)

    name  age
0   Arif   35
1  Nafis   30
2  Hasan   40


In [ ]:
print(df.loc[0]) #loc attribute

name    Arif
age       35
Name: 0, dtype: object


In [ ]:
#kind define kora in pandas , coreation relate